# Generated by Django 2.0 on 2018-02-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.utils.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('description', models.CharField(max_length=140)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent_id', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='news.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPics',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('text_content', models.TextField()),
                ('main_picture', models.ImageField(blank=True, null=True,
                                                   upload_to=news.utils.functions.main_news_pic)),
                ('author', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Author')),
                ('category', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='PublishedNews',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('main_picture', models.ImageField(blank=True, null=True,
                                                   upload_to=news.utils.functions.main_news_pic)),
                ('author', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.CASCADE, related_name='p_articles', to='news.Author')),
                ('category', models.OneToOneField(blank=True, null=True,
                                                  on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
                ('draft_news', models.OneToOneField(blank=True, null=True,
                                                    on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'verbose_name_plural': 'published news',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='publishednews',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='news.Tag'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='news.Tag'),
        ),
        migrations.AddField(
            model_name='extrapics',
            name='news',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='extra_pics', to='news.News'),
        ),
    ]
