# Generated by Django 2.0 on 2018-02-03 11:51

from django.db import migrations, models
import django.db.models.deletion
import news.utilfuncs


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='additional_pictures',
            field=models.ImageField(blank=True, null=True, upload_to=news.utilfuncs.news_pics),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to=news.utilfuncs.main_news_pic),
        ),
    ]
