# Generated by Django 2.0 on 2018-02-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednews',
            name='draft_news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='published_news', serialize=False, to='news.News'),
        ),
    ]
