# Generated by Django 2.0 on 2018-02-04 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Category'),
        ),
    ]
