# Generated by Django 2.0.2 on 2018-03-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180219_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='DraftNews',
        ),
        migrations.RemoveField(
            model_name='publishednews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publishednews',
            name='category',
        ),
        migrations.RemoveField(
            model_name='publishednews',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='publishednews',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='publishednews',
            name='main_picture',
        ),
        migrations.RemoveField(
            model_name='publishednews',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='publishednews',
            name='text_content',
        ),
    ]
