# Generated by Django 2.0 on 2018-02-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180204_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='additional_pictures',
        ),
        migrations.AddField(
            model_name='extrapics',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pics', to='news.News'),
        ),
    ]
